AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'Prod'

Globals:
  Function:
    Runtime: python3.9
    Handler: index.handler
    Timeout: 3

Resources:

  # ============================================================
  # API GATEWAY
  # ============================================================

  ServerlessBotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunc.Arn
            FunctionInvokeRole: !GetAtt AuthorizerFuncRole.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: false

  # ============================================================
  # LAMBDA
  # ============================================================

  # Authorizers

  AuthorizerFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/auth

  # Events

  EventDelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
      CodeUri: gen/events/delete
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /events
            Method: delete

  EventGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/events/get/
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /events
            Method: get

  EventPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/events/post/
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /events
            Method: post

Outputs:
  ServerlessBotApi:
    Description: "Main API"
    Value: !Sub "https://${ServerlessBotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events"
