AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'Prod'

Globals:
  Function:
    Runtime: python3.9
    Handler: index.handler
    Timeout: 3

Resources:

  # ============================================================
  # API GATEWAY
  # ============================================================

  ServerlessBotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage

  # ============================================================
  # LAMBDA
  # ============================================================

  CalendarEventDelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
      CodeUri: gen/calendar/events/delete
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /calendar
            Method: delete

  CalendarEventGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/calendar/events/get/
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /calendar
            Method: get

  CalendarEventPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/calendar/events/post/
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessBotApi
            Path: /calendar
            Method: post

Outputs:
  ServerlessBotApi:
    Value: !Sub "https://${ServerlessBotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calendar"
  
  CalendarEventDelete:
    Value: !GetAtt CalendarEventDelete.Arn
  CalendarEventGet:
    Value: !GetAtt CalendarEventGet.Arn
  CalendarEventPost:
    Value: !GetAtt CalendarEventPost.Arn
  
